#' Returns dataframe with heart rate information for a range of dates
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param date_start Start date specified in the format "yyyy-MM-dd"
#' @param date_end End date specified in the format "yyyy-MM-dd"
#' @param detail_level Number of data points to include. Either "1sec" or "1min".
#'
#' @return df
#' @export
#'
get_heart_rate_intraday_time_series_multiple <- function(token, date_start, date_end, detail_level = "1min") {

  dates <- seq(from = lubridate::ymd(date_start), to = lubridate::ymd(date_end), by = '1 day')
  d <- dates %>%
    purrr::map(get_heart_rate_intraday_time_series_add_day, token = token, detail_level = detail_level) %>%
    purrr::map_df(dplyr::bind_rows)

}

get_heart_rate_intraday_time_series_add_day <- function(token, date, detail_level = "1min", start_time = NULL,
                                                        end_time = NULL, simplify = TRUE)  {
  df <- get_heart_rate_intraday_time_series(token, date, detail_level, start_time, end_time, simplify)
  df <- data.frame(df)
  df[["day"]] <- date
  return(df)
}




